# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

"""
Secret redaction and safe environment construction for git invocations.

Holds the token patterns used to scrub credentials out of anything that
may be logged or raised, plus the constants describing the GIT_ASKPASS
helper contract (the script itself is executed by
:func:`dependamerge.git_ops.git_askpass_env`).
"""

from __future__ import annotations

import os
import re
from collections.abc import Sequence

# SECURITY: Token redaction patterns cover all known GitHub token formats,
# GitLab tokens, and JWT-like tokens. Keep this list up to date when new
# token prefixes are introduced. See git_ops module docstring for design goals.
_TOKEN_PATTERNS = [
    re.compile(r"ghp_[A-Za-z0-9]{20,}", re.IGNORECASE),  # GitHub PAT (classic)
    re.compile(r"ghs_[A-Za-z0-9]{20,}", re.IGNORECASE),  # GitHub App installation
    re.compile(r"ghu_[A-Za-z0-9]{20,}", re.IGNORECASE),  # GitHub user-to-server
    re.compile(r"github_pat_[A-Za-z0-9_]{20,}", re.IGNORECASE),  # fine-grained
    re.compile(r"glpat-[A-Za-z0-9_-]{20,}", re.IGNORECASE),  # GitLab PAT
    # JWT-like long tokens (best-effort)
    re.compile(r"[A-Za-z0-9-_]{20,}\.[A-Za-z0-9-_]{20,}\.[A-Za-z0-9-_]{10,}"),
]
# http(s)://user:password@host
_BASIC_AUTH_IN_URL = re.compile(r"(https?://[^:/@\s]+:)([^@/\s]+)(@)", re.IGNORECASE)
# x-access-token:<token>@ in URL
_X_ACCESS_TOKEN_IN_URL = re.compile(r"(x-access-token:)([^@]+)(@)", re.IGNORECASE)


def _redact(text: str) -> str:
    """Redact likely secrets (tokens/passwords) from a string."""
    if not text:
        return text
    # Basic auth password redaction
    text = _BASIC_AUTH_IN_URL.sub(r"\1***\3", text)
    # x-access-token redaction
    text = _X_ACCESS_TOKEN_IN_URL.sub(r"\1***\3", text)
    # Token patterns
    for pat in _TOKEN_PATTERNS:
        text = pat.sub("***", text)
    return text


def redact_text(text: str) -> str:
    """Public helper: redact likely secrets (tokens/passwords) from a string.

    Exposed so downstream consumers can apply the same redaction rules
    to values they log themselves (e.g. remote URLs read back from git
    configuration).
    """
    return _redact(text)


def _redact_seq(parts: Sequence[str]) -> Sequence[str]:
    """Redact secrets from a sequence of strings."""
    return [(_redact(p) if isinstance(p, str) else p) for p in parts]


def _build_git_env(
    env_overrides: dict[str, str] | None = None, *, lfs_skip: bool = True
) -> dict[str, str]:
    """Build a safe environment for git invocations."""
    env = os.environ.copy()

    # Never inherit the internal askpass token/username from the parent
    # process. A stale value (e.g. left by an external wrapper or an
    # earlier run) must not leak into git subprocesses when no token is
    # requested. A legitimate per-operation token is re-applied below
    # from env_overrides (see git_askpass_env / run_git).
    env.pop(_ASKPASS_TOKEN_ENV, None)
    env.pop(_ASKPASS_USERNAME_ENV, None)

    # Avoid interactive auth prompts inside automation
    env.setdefault("GIT_TERMINAL_PROMPT", "0")

    # Speed up clones when LFS is present; callers can disable if needed
    if lfs_skip:
        env.setdefault("GIT_LFS_SKIP_SMUDGE", "1")

    # Allow overrides (but do not allow overriding security toggles to unsafe defaults)
    if env_overrides:
        for k, v in env_overrides.items():
            env[k] = v

    return env


# Environment variable names used by the GIT_ASKPASS helper script.
# The token is passed to the askpass helper via the environment, never
# via argv or on-disk files. Note: environment variables are not fully
# confidential (same-UID and privileged processes can inspect them);
# the concrete guarantees are no argv exposure and no on-disk
# persistence.
_ASKPASS_TOKEN_ENV = "DM_GIT_ASKPASS_TOKEN"
_ASKPASS_USERNAME_ENV = "DM_GIT_ASKPASS_USERNAME"
# Non-secret default username used to answer git username prompts
# (suitable for GitHub tokens).
_ASKPASS_DEFAULT_USERNAME = "x-access-token"

# POSIX shell askpass helper. Git invokes it with the credential prompt
# as $1 ("Username for ..." / "Password for ..."). The script itself
# contains no secret: it answers username prompts with a configurable,
# non-secret username and everything else with the token taken from the
# environment of the invoking git process. The variable names are
# interpolated from the constants above so there is a single source of
# truth (renaming a constant cannot silently desync the script).
_ASKPASS_SCRIPT = f"""#!/bin/sh
# Auto-generated by dependamerge git_ops; supplies git credentials from
# the environment so secrets never appear in argv or on disk.
case "$1" in
    [Uu]sername*) printf '%s\\n' "${{{_ASKPASS_USERNAME_ENV}:-{_ASKPASS_DEFAULT_USERNAME}}}" ;;
    *) printf '%s\\n' "${{{_ASKPASS_TOKEN_ENV}}}" ;;
esac
"""
